trigger:
  - main

pool: 
 name: agent-pool


stages:
  - stage: maven_compile
    displayName: maven_compile
    jobs:
      - job: maven_compile
        displayName: maven_compile
        steps:
        - task: Maven@4
          inputs:
            azureSubscription: 'azure-sc'
            mavenPomFile: 'pom.xml'
            goals: 'compile'
            publishJUnitResults: true
            testResultsFiles: '**/surefire-reports/TEST-*.xml'
            javaHomeOption: 'JDKVersion'
            mavenVersionOption: 'Default'
            mavenAuthenticateFeed: false
            effectivePomSkip: false
            sonarQubeRunAnalysis: false
            sqMavenPluginVersionChoice: 'latest'
  - stage: maven_test
    displayName: maven_test
    jobs:
      - job: maven_test
        displayName: maven_test
        steps:
        - task: Maven@4
          inputs:
            azureSubscription: 'azure-sc'
            mavenPomFile: 'pom.xml'
            options: 'test'
            publishJUnitResults: true
            testResultsFiles: '**/surefire-reports/TEST-*.xml'
            javaHomeOption: 'JDKVersion'
            mavenVersionOption: 'Default'
            mavenAuthenticateFeed: false
            effectivePomSkip: false
            sonarQubeRunAnalysis: false
            sqMavenPluginVersionChoice: 'latest'