trigger:
  none

pool:
  name: agent-pool-sh
  demands: 
    - maven

stages:
  - stage: compile 
    displayName: 'maven compile'
    jobs:
      - job: maven_compile
        steps:
        - task: Maven@4
          inputs:
            azureSubscription: 'azure-sc'
            mavenPomFile: 'pom.xml'
            goals: 'compile'
            publishJUnitResults: true
            testResultsFiles: '**/surefire-reports/TEST-*.xml'
            javaHomeOption: 'JDKVersion'
            mavenVersionOption: 'Default'
            mavenAuthenticateFeed: false
            effectivePomSkip: false
            sonarQubeRunAnalysis: false
  - stage: test
    displayName: 'Maven test'
    jobs:
      - job: 'unit_test'
        steps:
        - task: Maven@4
          inputs:
            azureSubscription: 'azure-sc'
            mavenPomFile: 'pom.xml'
            goals: 'test'
            publishJUnitResults: true
            testResultsFiles: '**/surefire-reports/TEST-*.xml'
            javaHomeOption: 'JDKVersion'
            mavenVersionOption: 'Default'
            mavenAuthenticateFeed: false
            effectivePomSkip: false
            sonarQubeRunAnalysis: false
  - stage: trivy_scan
    displayName: trivy_scan
    jobs:
      - job: trivy_scan
        steps:
        - task: CmdLine@2
          inputs:
            script: 'trivy fs --format table -o fs.html .'
  - stage: SonarQube
    displayName: Sonar_Test
    jobs:
      - job: SonarQube
        steps:
        - task: SonarQubePrepare@7
          inputs:
            SonarQube: 'sonar-sc1'
            scannerMode: 'cli'
            configMode: 'manual'
            cliProjectKey: 'Multi-Tier-With-Database-p_Multi-Tier-With-Database-p_432df0bf-903d-4be1-be34-8462ad438f4c'
            cliProjectName: 'Multi-Tier-With-Database-p'
            cliSources: '.'
            extraProperties: 'sonar.java.binaries=target/classes'
      
        - task: SonarQubeAnalyze@7
          inputs:
            jdkversion: 'JAVA_HOME_17_X64'
  - stage: Publish_artifact
    displayName: Publish_artifact
    jobs:
      - job: Publish_artifact
        displayName: Publish_artifact
        steps:
        - task: Maven@4
          inputs:
            azureSubscription: 'azure-sc'
            mavenPomFile: 'pom.xml'
            goals: 'deploy'
            publishJUnitResults: true
            testResultsFiles: '**/surefire-reports/TEST-*.xml'
            javaHomeOption: 'JDKVersion'
            mavenVersionOption: 'Default'
            mavenAuthenticateFeed: false
            effectivePomSkip: false
            sonarQubeRunAnalysis: false
        - task: MavenAuthenticate@0
          inputs:
            artifactsFeeds: 'artifact-feed'