trigger:
  none

pool:
  name: agent-pool-sh
  demands: 
    - maven

stages:
  - stage: maven_compile 
    displayName: 'maven compile'
    jobs:
      - job: maven_compile
        steps:
        - task: Maven@4
          inputs:
            azureSubscription: 'azure-sc'
            mavenPomFile: 'pom.xml'
            goals: 'compile'
            publishJUnitResults: true
            testResultsFiles: '**/surefire-reports/TEST-*.xml'
            javaHomeOption: 'JDKVersion'
            mavenVersionOption: 'Default'
            mavenAuthenticateFeed: false
            effectivePomSkip: false
            sonarQubeRunAnalysis: false
  - stage: JUnit_Test
    displayName: 'Maven test'
    jobs:
      - job: 'unit_test'
        steps:
        - task: Maven@4
          inputs:
            azureSubscription: 'azure-sc'
            mavenPomFile: 'pom.xml'
            goals: 'test'
            publishJUnitResults: true
            testResultsFiles: '**/surefire-reports/TEST-*.xml'
            javaHomeOption: 'JDKVersion'
            mavenVersionOption: 'Default'
            mavenAuthenticateFeed: false
            effectivePomSkip: false
            sonarQubeRunAnalysis: false
  - stage: trivy_scan
    displayName: trivy_scan
    jobs:
      - job: trivy_scan
        steps:
        - task: CmdLine@2
          inputs:
            script: 'trivy fs --format table -o fs.html .'
 
  - stage: sonar_analysis
    displayName: sonar_analysis
    jobs:
      - job: sonar_analysis
        steps:
        - task: SonarQubePrepare@7
          inputs:
            SonarQube: 'sonar-svc99'
            scannerMode: 'other'
            extraProperties: |
              # Additional properties that will be passed to the scanner,
              # Put one key=value per line, example:
              # sonar.exclusions=**/*.bin
              sonar.projectKey=Multi-Tier-With-Database-p_Multi-Tier-With-Database-p_AZaZrEmkGmit7bDMTcx_

        - task: JavaToolInstaller@1
          inputs:
            versionSpec: '21'
            jdkArchitectureOption: 'x64'
            jdkSourceOption: 'PreInstalled'
        
        - task: Maven@4
          inputs:
            azureSubscription: 'azure-sc'
            mavenPomFile: 'pom.xml'
            publishJUnitResults: true
            testResultsFiles: '**/surefire-reports/TEST-*.xml'
            javaHomeOption: 'JDKVersion'
            mavenVersionOption: 'Default'
            mavenAuthenticateFeed: false
            effectivePomSkip: false
            sonarQubeRunAnalysis: true
            sqMavenPluginVersionChoice: 'latest'
        
        - task: SonarQubePublish@7
          inputs:
            pollingTimeoutSec: '300'
        
  - stage: Publish_build_artifact
    displayName: Publish_build_artifact
    jobs:
      - job: Publish_build_artifact
        displayName: Publish_build_artifact
        steps:
        - task: MavenAuthenticate@0
          inputs:
            artifactsFeeds: 'artifact-feed'
        - task: Maven@4
          inputs:
            azureSubscription: 'azure-sc'
            mavenPomFile: 'pom.xml'
            goals: 'deploy'
            publishJUnitResults: true
            testResultsFiles: '**/surefire-reports/TEST-*.xml'
            javaHomeOption: 'JDKVersion'
            mavenVersionOption: 'Default'
            mavenAuthenticateFeed: false
            effectivePomSkip: false
            sonarQubeRunAnalysis: false
  - stage: docker_build
    displayName: docker_build
    jobs:
      - job: docker_build
        steps:
        - task: CmdLine@2
          inputs:
            script: 'mvn package'
        - task: Docker@2
          inputs:
            containerRegistry: 'acr-sc'
            repository: 'dev'
            command: 'build'
            Dockerfile: '**/Dockerfile'
            tags: 'latest'
  - stage: trivy_image_scan
    displayName: trivy_image_scan
    jobs:
      - job: trivy_image_scan
        displayName: trivy_image_scan
        steps:
        - task: CmdLine@2
          inputs:
            script: 'trivy image --format table -o image.html acr1122.azurecr.io/dev:latest'
  
  - stage: docker_image_publish_to_acr
    displayName: docker_image_publish_to_acr
    jobs:
      - job: docker_image_publish_to_acr
        steps:
        - task: Docker@2
          inputs:
            containerRegistry: 'acr-sc'
            repository: 'dev'
            command: 'push'
            tags: 'latest'
  
  - stage: Deploy_to_aks
    displayName: Deploy_to_aks
    jobs:
      - job: Deploy_to_aks
        steps:
        - task: KubernetesManifest@1
          inputs:
            action: 'deploy'
            connectionType: 'kubernetesServiceConnection'
            kubernetesServiceConnection: 'k8-sc'
            namespace: 'default'
            manifests: 'ds.yml'