trigger:
  none

pool:
  name: agent-pool-sh
  demands: Agent.Name -equals agent-sh

stages:
  - stage: compile 
    displayName: 'maven compile'
    jobs:
      - job: maven_compile
        steps:
        - task: Maven@4
          inputs:
            azureSubscription: 'azure-sc'
            mavenPomFile: 'pom.xml'
            goals: 'compile'
            publishJUnitResults: true
            testResultsFiles: '**/surefire-reports/TEST-*.xml'
            javaHomeOption: 'JDKVersion'
            mavenVersionOption: 'Default'
            mavenAuthenticateFeed: false
            effectivePomSkip: false
            sonarQubeRunAnalysis: false
  - stage: test
    displayName: 'Maven test'
    jobs:
      - job: 'unit_test'
        steps:
        - task: Maven@4
          inputs:
            azureSubscription: 'azure-sc'
            mavenPomFile: 'pom.xml'
            goals: 'test'
            publishJUnitResults: true
            testResultsFiles: '**/surefire-reports/TEST-*.xml'
            javaHomeOption: 'JDKVersion'
            mavenVersionOption: 'Default'
            mavenAuthenticateFeed: false
            effectivePomSkip: false
            sonarQubeRunAnalysis: false