trigger:
  none

pool:
  name: agent-pool-sh
  demands: 
    - maven

stages:
  - stage: compile 
    displayName: 'maven compile'
    jobs:
      - job: maven_compile
        steps:
        - task: Maven@4
          inputs:
            azureSubscription: 'azure-sc'
            mavenPomFile: 'pom.xml'
            goals: 'compile'
            publishJUnitResults: true
            testResultsFiles: '**/surefire-reports/TEST-*.xml'
            javaHomeOption: 'JDKVersion'
            mavenVersionOption: 'Default'
            mavenAuthenticateFeed: false
            effectivePomSkip: false
            sonarQubeRunAnalysis: false
  - stage: test
    displayName: 'Maven test'
    jobs:
      - job: 'unit_test'
        steps:
        - task: Maven@4
          inputs:
            azureSubscription: 'azure-sc'
            mavenPomFile: 'pom.xml'
            goals: 'test'
            publishJUnitResults: true
            testResultsFiles: '**/surefire-reports/TEST-*.xml'
            javaHomeOption: 'JDKVersion'
            mavenVersionOption: 'Default'
            mavenAuthenticateFeed: false
            effectivePomSkip: false
            sonarQubeRunAnalysis: false
  
  - stage: sonarQube
    displayName: 'Sonar Qube Analysis'
    jobs:
      - job: SonarQube_analysis
        steps: 
        - task: SonarQubePrepare@7
          inputs:
            SonarQube: 'sonarQube-sc'
            scannerMode: 'cli'
            configMode: 'manual'
            cliProjectKey: 'anyname'
            cliProjectName: 'anyname'
            cliSources: '.'
            extraProperties: 'sonar.java.binaries=.'
        
        - task: SonarQubeAnalyze@7
          inputs:
            jdkversion: 'JAVA_HOME_17_X64'