trigger:
  - main

pool: 
 name: agent-pool


stages:
  - stage: maven_compile
    displayName: maven_compile
    jobs:
      - job: maven_compile
        displayName: maven_compile
        steps:
        - task: Maven@4
          inputs:
            azureSubscription: 'azure-sc'
            mavenPomFile: 'pom.xml'
            goals: 'compile'
            publishJUnitResults: true
            testResultsFiles: '**/surefire-reports/TEST-*.xml'
            javaHomeOption: 'JDKVersion'
            mavenVersionOption: 'Default'
            mavenAuthenticateFeed: false
            effectivePomSkip: false
            sonarQubeRunAnalysis: false
  - stage: maven_test
    displayName: maven_test
    jobs:
      - job: maven_test
        displayName: maven_test
        steps:
        - task: Maven@4
          inputs:
            azureSubscription: 'azure-sc'
            mavenPomFile: 'pom.xml'
            options: 'test'
            publishJUnitResults: true
            testResultsFiles: '**/surefire-reports/TEST-*.xml'
            javaHomeOption: 'JDKVersion'
            mavenVersionOption: 'Default'
            mavenAuthenticateFeed: false
            effectivePomSkip: false
            sonarQubeRunAnalysis: false
  
  - stage: trivy_scan
    displayName: trivy_test
    jobs:
      - job: trivy_test
        displayName: trivy_test
        steps:
        - task: CmdLine@2
          inputs:
            script: 'trivy fs . --format table -o fs.html'
 
  - stage: publish_artifact
    displayName: publish_artifact
    jobs:
      - job: publish_artifact
        steps:
        - task: MavenAuthenticate@0
          inputs:
            artifactsFeeds: 'afticat-feed4'
        - task: Maven@4
          inputs:
            azureSubscription: 'azure-sc'
            mavenPomFile: 'pom.xml'
            goals: 'publish'
            publishJUnitResults: true
            testResultsFiles: '**/surefire-reports/TEST-*.xml'
            javaHomeOption: 'JDKVersion'
            mavenVersionOption: 'Default'
            mavenAuthenticateFeed: false
            effectivePomSkip: false
            sonarQubeRunAnalysis: false

 
  - stage: Docker_buid
    displayName: Docker_buid
    jobs:
      - job: Docker_buid
        steps:
        - task: Docker@2
          inputs:
            containerRegistry: 'acr-svc4'
            repository: 'may4'
            command: 'build'
            Dockerfile: '**/Dockerfile'
            tags: 'latest'
            
  - stage: trivy_image_scan
    displayName: trivy_image_scan
    jobs:
      - job: trivy_image_scan
        steps:
        - task: CmdLine@2
          inputs:
            script: 'trivy image --format table -o image.html'

  - stage: Docker_image_publish
    displayName: Docker_image_publish
    jobs:
      - job: Docker_image_publish
        steps:
        - task: Docker@2
          inputs:
            containerRegistry: 'acr-svc4'
            repository: 'may4'
            command: 'push'
            tags: 'latest'
  
 